### PR TITLE
Fix/add compatibility product add on gravity add on

### PR DESCRIPTION
**Pull request by alexiglesias31**
### All Submissions:

* [x] Does your code follow the [Extendables](https://extendomattic.wordpress.com/standardizations/) standards?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

Fix compatibility issues with Woo Product Add-On and Gravity Forms Add-On

### How to test the changes in this Pull Request:

1. Install a built version of this PR.
2. Install and setup Gravity Forms Add-On and Product Add-On.
3. The extra fees added by the Add-On should be added as well using the Express Checkout from the product page.

### Changelog entry

> Fix - Compatibility with Woo Product Add-On
> Fix - Compatibility with WooCommerce Gravity Forms Product Add-Ons

### CODE REVIEW

**Review by dpanta94 — APPROVED** [review]
LGTM!

**Review by dpanta94 — APPROVED** [review]
LGTM!

**Comment by alexiglesias31** [comment]
@dpanta94 some extra fixes for the following issues:
- https://app.clickup.com/t/86drg2pgh
- https://app.clickup.com/t/86drgg6zx
- https://app.clickup.com/t/86drgqht4

**Review by dpanta94 — APPROVED** [review]
LGTM!

**Pull request merged**
